### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by vahid45** [Couchiman/CRMSSIS#18]
i have error when create new connection that is my connection
authentication type : Active Directory
org uri : http://servername/orgname port 80
domain : domain
user:user
pass:pass

when set this connection to source or destination my vs crash and close.
this is vs error:
An error occurred while retrieving the value of property "ConnectionString". The error code is 0x80020009 "Invalid URI: The hostname could not be parsed.".
 (Microsoft Visual Studio)

this is event viewer log:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32)
   at CRMSSIS.CRMSourceAdapter.CRMSourceAdapterUIForm.CRMSourceAdapterUIForm_Load(System.Object, System.EventArgs)
   at System.Windows.Forms.Form.OnLoad(System.EventArgs)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by Couchiman** [comment]
dont include http. connection mananger automatically determines type of protocol

**Comment by Couchiman** [comment]
use servername/orgname
user 
pass
